/**
 * LiveKit Agents agent definition.
 *
 * `defineVoiceAgent` returns the agent object placed as the default export of a
 * worker entry file. The framework runs it as a Job (one per call, in its own
 * process): it connects to the room, builds the NeuroLink brain via the
 * supplied factory, wires Silero VAD + STT/TTS plugins, and overrides `llmNode`
 * so every turn is generated by `neurolink.stream()`.
 *
 * `@livekit/agents` and the plugins are optional dependencies, imported
 * dynamically so the core package does not require them unless the LiveKit
 * voice agent is used. Type-only imports are erased at build time and add no
 * runtime dependency.
 *
 * See docs/features/livekit-voice-agent.md.
 */

import { ReadableStream } from "node:stream/web";
import type {
  Agent as JobAgent,
  JobContext,
  llm as llmNs,
  voice as voiceNs,
} from "@livekit/agents";
import { logger } from "../../utils/logger.js";
import { createVoiceBrain } from "./brain.js";
import { resolveBrainDefaults, resolveEouTurnDetection } from "./config.js";
import { attachEventBridge } from "./eventBridge.js";
import type {
  LiveKitSttConfig,
  LiveKitTtsConfig,
  LiveKitVadConfig,
  LiveKitVoiceAgentConfig,
  LiveKitVoiceBrain,
} from "../../types/index.js";

const DEFAULT_CONVERSATION_PREFIX = "voice";

// Turn-end timing defaults (approach A: silence tuning). Longer silence +
// endpointing floor so natural mid-sentence pauses ("...and so, [pause] um")
// don't end the turn early and split one utterance into two. Overridable via
// config (vad.minSilenceDuration / turn.minEndpointingDelay).
const DEFAULT_MIN_SILENCE_DURATION = 1.0; // seconds (Silero VAD)
const DEFAULT_MIN_ENDPOINTING_DELAY = 1000; // ms (framework endpointing floor)

/**
 * Find the most recent user utterance in a chat context.
 * Uses the `type === "message"` discriminant — no type assertions.
 */
function latestUserText(chatCtx: llmNs.ChatContext): string | undefined {
  const items = chatCtx.items;
  for (let i = items.length - 1; i >= 0; i -= 1) {
    const item = items[i];
    if (item.type === "message" && item.role === "user") {
      return item.textContent;
    }
  }
  return undefined;
}

/**
 * Build a text stream for a single turn from the brain, abortable on cancel.
 * When the framework cancels the stream (barge-in), the brain's turn is aborted.
 */
function brainTurnStream(
  brain: LiveKitVoiceBrain,
  transcript: string,
  conversationId: string,
  onAbortedBeforeOutput?: () => void,
): ReadableStream<string> {
  const controller = new AbortController();
  const generator = brain.streamReply({
    transcript,
    conversationId,
    signal: controller.signal,
  });
  const iterator = generator[Symbol.asyncIterator]();
  let producedOutput = false;

  return new ReadableStream<string>({
    async pull(streamController) {
      const next = await iterator.next();
      if (next.done === true) {
        streamController.close();
        return;
      }
      producedOutput = true;
      streamController.enqueue(next.value);
    },
    cancel() {
      controller.abort();
      if (!producedOutput) {
        onAbortedBeforeOutput?.();
      }
    },
  });
}

/**
 * Construct the English semantic EOU turn detector, or `undefined` if disabled.
 *
 * Layered on top of VAD: VAD detects acoustic silence, then this model decides
 * whether the user's turn is semantically complete, so natural mid-sentence
 * pauses don't split one utterance. Opt-in via `LIVEKIT_EOU_TURN_DETECTION`.
 * The runner is registered in the worker process (see `voiceAgentWorker.ts`);
 * here we only construct the model handle, which dispatches inference to the
 * shared executor via the running job context.
 */
async function loadEouTurnDetector(): Promise<
  voiceNs.AgentSession["turnDetection"] | undefined
> {
  const { enabled, unlikelyThreshold } = resolveEouTurnDetection();
  if (!enabled) {
    return undefined;
  }
  const { turnDetector } = await import("@livekit/agents-plugin-livekit");
  return new turnDetector.EnglishModel(unlikelyThreshold);
}

/**
 * Construct the Silero VAD instance for the session.
 *
 * Stricter-than-default thresholds so background noise isn't treated as speech
 * (a higher activation threshold and a minimum speech duration reject short,
 * quiet noise bursts).
 */
async function loadVad(
  config: LiveKitVadConfig | undefined,
): Promise<voiceNs.AgentSession["vad"]> {
  const silero = await import("@livekit/agents-plugin-silero");
  return silero.VAD.load({
    activationThreshold: config?.activationThreshold ?? 0.6,
    minSpeechDuration: config?.minSpeechDuration ?? 0.2,
    minSilenceDuration:
      config?.minSilenceDuration ?? DEFAULT_MIN_SILENCE_DURATION,
  });
}

/**
 * Construct the STT plugin instance from configuration.
 *
 * Only defined options are passed — passing `undefined` would override the
 * plugin's own defaults (e.g. its default model) with `undefined` and break it.
 */
async function buildStt(
  config: LiveKitSttConfig,
): Promise<voiceNs.AgentSession["stt"]> {
  if (config.provider === "soniox") {
    const soniox = await import("@livekit/agents-plugin-soniox");
    const opts: {
      model?: string;
      languageHints?: string[];
      languageHintsStrict?: boolean;
      maxEndpointDelayMs?: number;
    } = {};
    if (config.model !== undefined) {
      opts.model = config.model;
    }
    if (config.language !== undefined) {
      // Soft hint only: Soniox biases toward this language but can still
      // auto-detect another (e.g. the user switching to Telugu mid-call).
      // Do NOT set `languageHintsStrict` — forcing the hinted language makes
      // the realtime STT stall/error on other-language audio and the session
      // never recovers (no further transcripts, so no audio at all).
      opts.languageHints = [config.language];
    }
    if (config.maxEndpointDelayMs !== undefined) {
      opts.maxEndpointDelayMs = config.maxEndpointDelayMs;
    }
    return new soniox.STT(opts);
  }
  if (config.provider === "deepgram") {
    const deepgram = await import("@livekit/agents-plugin-deepgram");
    const opts: { language?: string } = {};
    if (config.language !== undefined) {
      opts.language = config.language;
    }
    return new deepgram.STT(opts);
  }
  throw new Error(
    `Unsupported LiveKit STT provider "${config.provider}" (supported: soniox, deepgram)`,
  );
}

/**
 * Construct the TTS plugin instance from configuration.
 *
 * Only defined options are passed — passing `undefined` would override the
 * plugin's own defaults (default voice/model) with `undefined` and break it.
 */
async function buildTts(
  config: LiveKitTtsConfig,
): Promise<voiceNs.AgentSession["tts"]> {
  if (config.provider === "cartesia") {
    const cartesia = await import("@livekit/agents-plugin-cartesia");
    const opts: { voice?: string; model?: string } = {};
    if (config.voice !== undefined) {
      opts.voice = config.voice;
    }
    if (config.model !== undefined) {
      opts.model = config.model;
    }
    return new cartesia.TTS(opts);
  }
  if (config.provider === "elevenlabs") {
    const elevenlabs = await import("@livekit/agents-plugin-elevenlabs");
    const opts: { voiceId?: string; modelID?: string } = {};
    if (config.voice !== undefined) {
      opts.voiceId = config.voice;
    }
    if (config.model !== undefined) {
      opts.modelID = config.model;
    }
    return new elevenlabs.TTS(opts);
  }
  throw new Error(
    `Unsupported LiveKit TTS provider "${config.provider}" (supported: cartesia, elevenlabs)`,
  );
}

/**
 * Define a LiveKit voice agent backed by NeuroLink.
 *
 * Place the result as the default export of the worker entry file:
 *
 * ```ts
 * export default defineVoiceAgent({
 *   createNeuroLink: async () => buildConfiguredNeuroLink(),
 *   stt: { provider: "deepgram" },
 *   tts: { provider: "elevenlabs" },
 * });
 * ```
 */
export function defineVoiceAgent(config: LiveKitVoiceAgentConfig): JobAgent {
  const defaults = resolveBrainDefaults();
  const provider = config.provider ?? defaults.provider;
  const model = config.model ?? defaults.model;
  const conversationPrefix =
    config.conversationIdPrefix ?? DEFAULT_CONVERSATION_PREFIX;

  async function entry(ctx: JobContext): Promise<void> {
    const entryStartedAt = Date.now();
    await ctx.connect();
    logger.debug(
      `[LiveKitVoiceAgent] Joined room "${ctx.room.name}" in ${Date.now() - entryStartedAt}ms`,
    );
    // When the user actually stopped speaking (VAD), used to measure how long
    // the agent waited after speech before committing the turn to the LLM.
    let userStoppedSpeakingAt: number | undefined;

    const neurolink = await config.createNeuroLink();
    const brain = createVoiceBrain({
      neurolink,
      provider,
      model,
      systemPrompt: config.systemPrompt,
      temperature: config.temperature,
      maxTokens: config.maxTokens,
      userId: config.userId,
    });

    const conversationId = `${conversationPrefix}-${ctx.room.name ?? ctx.job.id}`;

    const { voice, llm } = await import("@livekit/agents");
    const [vad, stt, tts, eouTurnDetector] = await Promise.all([
      loadVad(config.vad),
      buildStt(config.stt),
      buildTts(config.tts),
      loadEouTurnDetector(),
    ]);

    const transcriptEventsEnabled =
      config.events?.enabled === true &&
      typeof neurolink.getEventEmitter === "function";
    const transcriptEmitter = transcriptEventsEnabled
      ? neurolink.getEventEmitter?.()
      : undefined;
    let userTranscriptBuffer = "";
    let pendingPrefix = "";

    function emitUserTranscriptSegment(
      segmentText: string,
      isFinal: boolean,
    ): void {
      if (transcriptEmitter === undefined) {
        return;
      }
      const trimmed = segmentText.trim();
      if (isFinal) {
        userTranscriptBuffer =
          userTranscriptBuffer.length > 0
            ? `${userTranscriptBuffer} ${trimmed}`
            : trimmed;
        transcriptEmitter.emit("voice:user-transcript", {
          text: userTranscriptBuffer,
          final: false,
        });
        return;
      }

      const live =
        userTranscriptBuffer.length > 0
          ? `${userTranscriptBuffer} ${trimmed}`
          : trimmed;
      transcriptEmitter.emit("voice:user-transcript", {
        text: live,
        final: false,
      });
    }

    /**
     * Lock the user bubble at turn-end and reset the buffer for the next turn.
     * `replacesPrevious` tells the client this committed turn absorbed a prior
     * interrupted turn, so it should remove the orphaned previous user bubble.
     */
    function commitUserTranscript(
      finalText: string,
      replacesPrevious = false,
    ): void {
      if (transcriptEmitter !== undefined) {
        transcriptEmitter.emit("voice:user-transcript", {
          text: finalText,
          final: true,
          replacesPrevious,
        });
      }
      userTranscriptBuffer = "";
    }

    class NeuroLinkVoiceAgent extends voice.Agent {
      override async llmNode(
        chatCtx: llmNs.ChatContext,
        _toolCtx: llmNs.ToolContext,
        _modelSettings: voiceNs.ModelSettings,
      ): Promise<ReadableStream<llmNs.ChatChunk | string> | null> {
        const transcript = latestUserText(chatCtx);
        if (transcript === undefined || transcript.trim().length === 0) {
          userTranscriptBuffer = "";
          return null;
        }
        const hadPrefix = pendingPrefix.length > 0;
        const promptText = hadPrefix
          ? `${pendingPrefix} ${transcript}`
          : transcript;
        pendingPrefix = "";

        commitUserTranscript(promptText, hadPrefix);
        if (userStoppedSpeakingAt !== undefined) {
          logger.debug(
            `[LiveKitVoiceAgent] Endpointing waited ${Date.now() - userStoppedSpeakingAt}ms before sending turn to LLM`,
          );
        }
        return brainTurnStream(brain, promptText, conversationId, () => {
          // Interrupted before producing any reply → carry this turn's text
          // forward; the next turn merges it (prompt + UI).
          pendingPrefix = promptText;
        });
      }
    }

    class PlaceholderLLM extends llm.LLM {
      label(): string {
        return "neurolink-placeholder";
      }
      chat(): llmNs.LLMStream {
        throw new Error(
          "PlaceholderLLM.chat must not be called — llmNode overrides generation",
        );
      }
    }

    const turnHandling: NonNullable<
      ConstructorParameters<typeof voice.AgentSession>[0]
    >["turnHandling"] = {
      interruption: {
        minWords: config.interruption?.minWords ?? 2,
        minDuration: config.interruption?.minDuration ?? 600,
      },
    };
    if (eouTurnDetector !== undefined) {
      turnHandling.turnDetection = eouTurnDetector;
      logger.info(
        "[LiveKitVoiceAgent] Semantic end-of-utterance turn detection enabled (English)",
      );
    } else if (config.turn?.mode) {
      turnHandling.turnDetection = config.turn.mode;
    }
    const endpointing: { minDelay?: number; maxDelay?: number } = {};
    endpointing.minDelay =
      config.turn?.minEndpointingDelay ?? DEFAULT_MIN_ENDPOINTING_DELAY;
    if (config.turn?.maxEndpointingDelay !== undefined) {
      endpointing.maxDelay = config.turn.maxEndpointingDelay;
    }
    if (Object.keys(endpointing).length > 0) {
      turnHandling.endpointing = endpointing;
    }

    const session = new voice.AgentSession({
      vad,
      stt,
      tts,
      llm: new PlaceholderLLM(),
      turnHandling,
      // Do NOT speculatively call the LLM on preflight transcripts before the
      // turn ends — with NeuroLink as the brain each call is a real LLM request,
      // and it makes the agent feel like it responds while you're still talking.
      preemptiveGeneration: false,
    });
    const agent = new NeuroLinkVoiceAgent({
      instructions: config.systemPrompt ?? "",
    });

    // Inactivity watchdog: shut the per-call Job down after a stretch with no
    // user or agent activity (mirrors Clairvoyance). On timeout `ctx.shutdown`
    // runs the shutdown callbacks (disposing the bridge) and the Job process
    // exits — freeing its RAM and the EOU model — while the browser observes a
    // room disconnect. Reset on every interaction below. Configure via
    // VOICE_INACTIVITY_TIMEOUT_MS (default 10 min); <= 0 disables the watchdog.
    const inactivityTimeoutMs = Number(
      process.env.VOICE_INACTIVITY_TIMEOUT_MS ?? 600_000,
    );
    const inactivityEnabled =
      Number.isFinite(inactivityTimeoutMs) && inactivityTimeoutMs > 0;
    let inactivityTimer: ReturnType<typeof setTimeout> | undefined;
    let inactivityFired = false;
    function clearInactivityTimer(): void {
      if (inactivityTimer !== undefined) {
        clearTimeout(inactivityTimer);
        inactivityTimer = undefined;
      }
    }
    function noteActivity(): void {
      if (!inactivityEnabled || inactivityFired) {
        return;
      }
      clearInactivityTimer();
      inactivityTimer = setTimeout(() => {
        inactivityFired = true;
        logger.info(
          `[LiveKitVoiceAgent] Inactivity timeout (${Math.round(
            inactivityTimeoutMs / 1000,
          )}s) reached — shutting down job for room "${ctx.room.name}"`,
        );
        ctx.shutdown("inactivity timeout");
      }, inactivityTimeoutMs);
      // The watchdog must not, by itself, keep the event loop alive.
      inactivityTimer.unref?.();
    }
    ctx.addShutdownCallback(async () => {
      clearInactivityTimer();
    });

    // Track when the user actually stops speaking (VAD) so endpointing latency
    // can be measured, and reset the inactivity watchdog on user activity.
    session.on(voice.AgentSessionEventTypes.UserStateChanged, (ev) => {
      noteActivity();
      if (ev.oldState === "speaking" && ev.newState !== "speaking") {
        userStoppedSpeakingAt = Date.now();
      }
    });

    // Reset the inactivity watchdog on any agent speech/processing and on every
    // committed conversation item (user turn or agent reply), so the timeout
    // only fires during a genuine lull in the conversation.
    session.on(voice.AgentSessionEventTypes.AgentStateChanged, () => {
      noteActivity();
    });
    session.on(voice.AgentSessionEventTypes.ConversationItemAdded, () => {
      noteActivity();
    });

    // Forward user STT transcripts to the data-channel bridge as a single
    // live-updating bubble. `UserInputTranscribed` fires `isFinal: true` per
    // finalized SEGMENT (several per turn), so we never forward those as the
    // turn-final; `emitUserTranscriptSegment` accumulates them into the per-turn
    // buffer and emits `final: false`. The lone `final: true` is sent from
    // `llmNode` at the real turn boundary.
    if (transcriptEventsEnabled) {
      session.on(voice.AgentSessionEventTypes.UserInputTranscribed, (ev) => {
        emitUserTranscriptSegment(ev.transcript, ev.isFinal);
      });
    }

    logger.info("[LiveKitVoiceAgent] Session starting", {
      room: ctx.room.name,
      provider,
      model,
    });

    await session.start({ agent, room: ctx.room });

    // Start the inactivity countdown now that the session is live; every
    // interaction handler above re-arms it.
    noteActivity();

    // Data-channel event bridge: forward NeuroLink events (text, tool calls,
    // results, HITL prompts, status) to the browser, and accept HITL responses
    // back. Only when enabled and the instance exposes its event emitter.
    if (config.events?.enabled === true && neurolink.getEventEmitter) {
      const bridge = await attachEventBridge({
        room: ctx.room,
        emitter: neurolink.getEventEmitter(),
        options: config.events,
      });
      ctx.addShutdownCallback(async () => {
        bridge.dispose();
      });
    }
  }

  return { entry };
}
